import nyc.welles.minecraftbots.nsfwbot.NotSafeForWorkBot
import org.bukkit.event.EventPriority
import org.bukkit.event.player.AsyncPlayerChatEvent
import org.bukkit.entity.Player
import java.lang.UnsupportedOperationException
import nyc.welles.minecraftbots.Bot
import java.util.HashMap
import java.util.UUID
import org.bukkit.plugin.java.JavaPlugin
import nyc.welles.minecraftbots.MinecraftBots
import org.bukkit.configuration.file.FileConfiguration
import com.google.api.client.json.jackson2.JacksonFactory
import kotlin.jvm.Throws
import java.security.GeneralSecurityException
import java.io.IOException
import com.google.api.services.youtube.YouTube
import com.google.api.client.http.javanet.NetHttpTransport
import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport
import org.bukkit.Bukkit
import nyc.welles.minecraftbots.youtubebot.YoutubeBot
import com.google.api.services.youtube.model.SearchListResponse
import com.google.api.services.youtube.model.ResourceId
import nyc.welles.minecraftbots.SWBEvent
import nyc.welles.minecraftbots.SWBCommandHandler
import org.bukkit.command.CommandExecutor
import org.bukkit.command.CommandSender
import java.lang.Runnable
import nyc.welles.minecraftbots.serverwidemusic.SWMusicCommand
import java.lang.Exception